version: '3.8'

services:
  web:
    build: .
    expose:
      - "5000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Condor92!
      POSTGRES_DB: autos_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 